CREATE TABLE earthquakes (
    primary_id INT PRIMARY KEY AUTO_INCREMENT,
    mag INT null,
    place VARCHAR(1000) NOT NULL,
    title VARCHAR(1000) NOT NULL,
    date_time INT null,
    updated INT null,
    tz INT null,
    url VARCHAR(1000) NOT NULL,
    felt INT null,
    cdi FLOAT null,
    mmi INT null,
    alert VARCHAR(1000) NOT NULL,
    status VARCHAR(1000) NOT NULL,
    tsunami INT null,
    sig INT null,
    resource_type VARCHAR(1000) NOT NULL,
    latitude FLOAT  null,
    longitude FLOAT null,
    depth FLOAT null
);