"""empty message

Revision ID: 30a0d4b22212
Revises: 55464a272758
Create Date: 2014-06-27 10:39:14.030414

"""

# revision identifiers, used by Alembic.
revision = '30a0d4b22212'
down_revision = '55464a272758'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_on_code', 'earthquake')
    op.drop_index('index_on_date_time', 'earthquake')
    op.drop_index('index_on_date_time_raw', 'earthquake')
    op.drop_index('index_on_date_time_raw_and_mag', 'earthquake')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_on_date_time_raw_and_mag', 'earthquake', [u'date_time_raw', u'mag'], unique=False)
    op.create_index('index_on_date_time_raw', 'earthquake', [u'date_time_raw'], unique=False)
    op.create_index('index_on_date_time', 'earthquake', [u'date_time'], unique=False)
    op.create_index('index_on_code', 'earthquake', [u'code'], unique=False)
    ### end Alembic commands ###
