"""empty message

Revision ID: 55464a272758
Revises: None
Create Date: 2014-01-10 16:09:33.164480

"""

# revision identifiers, used by Alembic.
revision = '55464a272758'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
