"""empty message

Revision ID: a83d1530a1d
Revises: None
Create Date: 2014-01-08 14:24:25.891104

"""

# revision identifiers, used by Alembic.
revision = 'a83d1530a1d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
